#ifndef _FISHBOT_DRIVER_APP_PROTOCOL_PROTOCOL_PROTOCOL_DEFINE_H_
#define _FISHBOT_DRIVER_APP_PROTOCOL_PROTOCOL_PROTOCOL_DEFINE_H_

#include "fishbot/driver/app_protocol/proto/proto_v1.0.0.20220621.h"

#endif  // _FISHBOT_DRIVER_APP_PROTOCOL_PROTOCOL_PROTOCOL_DEFINE_H_